import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dashboard-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dashboard.com">dashboard</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Dashboard</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
